# Pandas_Indexing_and_Selection

 Indexing in Series (Indexers: loc, iloc)

* Selecting rows: ```df[start:stop]```
* Selecting columns: ```df['column']``` or ```df.column``` or ```df[['col_x', 'col_y']]```
    * ```df['column']``` or ```df.column``` return a series
    * ```df[['col_x', 'col_y']]``` returns a dataframe

### A. loc()    
Uses Location of the value for indexing

In [11]:
import pandas as pd
value = pd.Series(['a', 'b', 'c', 'e', 'f'], index=[1, 2, 3, 4, 5])
value

1    a
2    b
3    c
4    e
5    f
dtype: object

In [12]:
value.loc[1]

'a'

In [13]:
value.loc[1:3]

1    a
2    b
3    c
dtype: object

### B. iloc()
 
Uses index of the value

In [14]:
value.iloc[1]

'b'

In [15]:
data.iloc[1:3]

NameError: name 'data' is not defined

## 2. Data Selection in Dataframes

### A. Dataframe as a dictionary

In [16]:
import pandas as pd

In [17]:

area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})
population = pd.Series({'California': 38332521, 'Texas': 26448193,
                        'New York': 19651127, 'Florida': 19552860,
                        'Illinois': 12882135})
info = pd.DataFrame({'area':area, 'population':population})

info

              area  population
California  423967    38332521
Texas       695662    26448193
New York    141297    19651127
Florida     170312    19552860
Illinois    149995    12882135

In [18]:
info['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [19]:
info(['area'],['population'])

TypeError: 'DataFrame' object is not callable

In [ ]:
info['area' , 'population']

In [ ]:
info[['area','population']]

In [ ]:
info.area

In [ ]:
print(info.population)

#### Adding a new Attribute

In [ ]:
info['density'] = info['population'] / info['area']

info

In [ ]:
info['new'] = info['population'] * info['area']

info

### B. DataFrame as two-dimensional array

In [ ]:
info.values

In [ ]:
info.T             #transpose of orginal table

## 2. Indexing in Dataframe (Indexers: loc, iloc)

### A. loc()

In [ ]:
print(info)

In [ ]:
info.loc['Illinois', 'population']

In [ ]:
info.loc['New York','population']

In [ ]:
info.loc[:'Illinois', :'population']

In [ ]:
info.loc['Texas':'Florida', : ]

### B. iloc()

In [20]:
info.iloc[:3, :3]

              area  population
California  423967    38332521
Texas       695662    26448193
New York    141297    19651127

In [21]:
info.iloc[0, 2] = 100

info

IndexError: single positional indexer is out-of-bounds

In [22]:
info

              area  population
California  423967    38332521
Texas       695662    26448193
New York    141297    19651127
Florida     170312    19552860
Illinois    149995    12882135

 # sorting Dataframes

sorting can be done in two ways
1. Sorting by indicies 
2. sorting by values

In [23]:
import pandas as pd

In [24]:
df = pd.read_csv("C:\\Users\\Hp\\Desktop\\Nikhat\\datasets\\Housing.csv")

In [25]:
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
5,10850000,7500,3,3,1,yes,no,yes,no,yes,2,yes,semi-furnished
6,10150000,8580,4,3,4,yes,no,no,no,yes,2,yes,semi-furnished
7,10150000,16200,5,3,2,yes,no,no,no,no,0,no,unfurnished
8,9870000,8100,4,1,2,yes,yes,yes,no,yes,2,yes,furnished
9,9800000,5750,3,2,4,yes,yes,no,no,yes,1,yes,unfurnished
10,9800000,13200,3,1,2,yes,no,yes,no,yes,2,yes,furnished
11,9681000,6000,4,3,2,yes,yes,yes,yes,no,2,no,semi-furnished
12,9310000,6550,4,2,2,yes,no,no,no,yes,1,yes,semi-furnished
13,9240000,3500,4,2,2,yes,no,no,yes,no,2,no,furnished
14,9240000,7800,3,2,2,yes,no,no,no,no,0,yes,semi-furnished
15,9100000,6000,4,1,2,yes,no,yes,no,no,2,no,semi-furnished
16,9100000,6600,4,2,2,yes,yes,yes,no,yes,1,yes,unfurnished
17,8960000,8500,3,2,4,yes,no,no,no,yes,2,no,furnished
18,8890000,4600,3,2,2,yes,yes,no,no,yes,2,no,furnished
19,8855000,6420,3,2,2,yes,no,no,no,yes,1,yes,semi-furnished
20,8750000,4320,3,1,2,yes,no,yes,yes,no,2,no,semi-furnished
21,8680000,7155,3,2,1,yes,yes,yes,no,yes,2,no,unfurnished
22,8645000,8050,3,1,1,yes,yes,yes,no,yes,1,no,furnished
23,8645000,4560,3,2,2,yes,yes,yes,no,yes,1,no,furnished
24,8575000,8800,3,2,2,yes,no,no,no,yes,2,no,furnished
25,8540000,6540,4,2,2,yes,yes,yes,no,yes,2,yes,furnished
26,8463000,6000,3,2,4,yes,yes,yes,no,yes,0,yes,semi-furnished
27,8400000,8875,3,1,1,yes,no,no,no,no,1,no,semi-furnished
28,8400000,7950,5,2,2,yes,no,yes,yes,no,2,no,unfurnished
29,8400000,5500,4,2,2,yes,no,yes,no,yes,1,yes,semi-furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
515,2450000,3210,3,1,2,yes,no,yes,no,no,0,no,unfurnished
516,2450000,3240,2,1,1,no,yes,no,no,no,1,no,unfurnished
517,2450000,3000,2,1,1,yes,no,no,no,no,1,no,unfurnished
518,2450000,3500,2,1,1,yes,yes,no,no,no,0,no,unfurnished
519,2450000,4840,2,1,2,yes,no,no,no,no,0,no,unfurnished
520,2450000,7700,2,1,1,yes,no,no,no,no,0,no,unfurnished
521,2408000,3635,2,1,1,no,no,no,no,no,0,no,unfurnished
522,2380000,2475,3,1,2,yes,no,no,no,no,0,no,furnished
523,2380000,2787,4,2,2,yes,no,no,no,no,0,no,furnished
524,2380000,3264,2,1,1,yes,no,no,no,no,0,no,unfurnished
525,2345000,3640,2,1,1,yes,no,no,no,no,0,no,unfurnished
526,2310000,3180,2,1,1,yes,no,no,no,no,0,no,unfurnished
527,2275000,1836,2,1,1,no,no,yes,no,no,0,no,semi-furnished
528,2275000,3970,1,1,1,no,no,no,no,no,0,no,unfurnished
529,2275000,3970,3,1,2,yes,no,yes,no,no,0,no,unfurnished
530,2240000,1950,3,1,1,no,no,no,yes,no,0,no,unfurnished
531,2233000,5300,3,1,1,no,no,no,no,yes,0,yes,unfurnished
532,2135000,3000,2,1,1,no,no,no,no,no,0,no,unfurnished
533,2100000,2400,3,1,2,yes,no,no,no,no,0,no,unfurnished
534,2100000,3000,4,1,2,yes,no,no,no,no,0,no,unfurnished
535,2100000,3360,2,1,1,yes,no,no,no,no,1,no,unfurnished
536,1960000,3420,5,1,2,no,no,no,no,no,0,no,unfurnished
537,1890000,1700,3,1,2,yes,no,no,no,no,0,no,unfurnished
538,1890000,3649,2,1,1,yes,no,no,no,no,0,no,unfurnished
539,1855000,2990,2,1,1,no,no,no,no,no,1,no,unfurnished
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [26]:
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [27]:
# setting price as index 
df.set_index("stories",inplace = True)

In [28]:
df.head()

,price,area,bedrooms,bathrooms,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
stories,,,,,,,,,,,,
3,13300000,7420,4,2,yes,no,no,no,yes,2,yes,furnished
4,12250000,8960,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,yes,no,yes,no,no,2,yes,semi-furnished
2,12215000,7500,4,2,yes,no,yes,no,yes,3,yes,furnished
2,11410000,7420,4,1,yes,yes,yes,no,yes,2,no,furnished

#### sorting by index

In [29]:
df.sort_index (axis = 0, ascending  = False ).head(15)

,price,area,bedrooms,bathrooms,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
stories,,,,,,,,,,,,
4,6685000,6600,2,2,yes,no,yes,no,no,0,yes,furnished
4,6160000,4500,3,1,yes,no,no,no,yes,0,no,unfurnished
4,8400000,7000,3,1,yes,no,no,no,yes,2,no,semi-furnished
4,6195000,5500,3,2,yes,yes,no,no,yes,1,no,semi-furnished
4,6755000,6000,4,2,yes,no,no,no,yes,0,no,unfurnished
4,7980000,9000,4,2,yes,no,no,no,yes,2,no,furnished
4,7962500,6000,3,1,yes,yes,no,no,yes,2,no,unfurnished
4,7910000,6000,4,2,yes,no,no,no,yes,1,no,semi-furnished
4,7840000,6360,3,2,yes,no,no,no,yes,0,yes,furnished
4,7700000,6480,3,2,yes,no,no,no,yes,2,no,unfurnished
4,7700000,6000,4,2,yes,no,no,no,no,2,no,semi-furnished
4,7560000,6000,4,2,yes,no,no,no,yes,1,no,furnished
4,7525000,6000,3,2,yes,no,no,no,yes,1,no,furnished
4,7490000,6600,3,1,yes,no,no,no,yes,3,yes,furnished
4,7420000,7440,3,2,yes,no,no,no,no,1,yes,unfurnished

#### sorting by values

In [30]:
# instead of making price as index we can directly sort the values of price by this method 
df.reset_index(inplace = True )

In [31]:
df.head()

,stories,price,area,bedrooms,bathrooms,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,3,13300000,7420,4,2,yes,no,no,no,yes,2,yes,furnished
1,4,12250000,8960,4,4,yes,no,no,no,yes,3,no,furnished
2,2,12250000,9960,3,2,yes,no,yes,no,no,2,yes,semi-furnished
3,2,12215000,7500,4,2,yes,no,yes,no,yes,3,yes,furnished
4,2,11410000,7420,4,1,yes,yes,yes,no,yes,2,no,furnished

In [32]:
# sorting by price 
df.sort_values(by = "price", ascending = True ).head(10)

,stories,price,area,bedrooms,bathrooms,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
544,2,1750000,3850,3,1,yes,no,no,no,no,0,no,unfurnished
543,1,1750000,2910,3,1,no,no,no,no,no,0,no,furnished
542,1,1750000,3620,2,1,yes,no,no,no,no,0,no,unfurnished
541,1,1767150,2400,3,1,no,no,no,no,no,0,no,semi-furnished
540,1,1820000,3000,2,1,yes,no,yes,no,no,2,no,unfurnished
539,1,1855000,2990,2,1,no,no,no,no,no,1,no,unfurnished
538,1,1890000,3649,2,1,yes,no,no,no,no,0,no,unfurnished
537,2,1890000,1700,3,1,yes,no,no,no,no,0,no,unfurnished
536,2,1960000,3420,5,1,no,no,no,no,no,0,no,unfurnished
535,1,2100000,3360,2,1,yes,no,no,no,no,1,no,unfurnished

In [33]:
# sorting by area 
df.sort_values(by = "area", ascending = False ).head(10)

,stories,price,area,bedrooms,bathrooms,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
7,2,10150000,16200,5,3,yes,no,no,no,no,0,no,unfurnished
125,1,5943000,15600,3,1,yes,no,no,no,yes,2,no,semi-furnished
66,1,6930000,13200,2,1,yes,no,yes,yes,no,1,no,furnished
10,2,9800000,13200,3,1,yes,no,yes,no,yes,2,yes,furnished
403,1,3500000,12944,3,1,yes,no,no,no,no,0,no,unfurnished
211,1,4900000,12900,3,1,yes,no,no,no,no,2,no,furnished
69,2,6790000,12090,4,2,yes,no,no,no,no,2,yes,furnished
129,3,5873000,11460,3,1,yes,no,no,no,no,2,yes,semi-furnished
56,2,7343000,11440,4,1,yes,no,yes,no,no,1,yes,semi-furnished
186,2,5110000,11410,2,1,yes,no,no,no,no,0,yes,furnished

In [34]:
# sorting multiple columns 

df.sort_values(by = ["bedrooms", "price"], ascending = False )

,stories,price,area,bedrooms,bathrooms,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
112,2,6083000,4300,6,2,yes,no,no,no,no,0,no,furnished
395,2,3500000,3600,6,1,yes,no,no,no,no,1,no,unfurnished
7,2,10150000,16200,5,3,yes,no,no,no,no,0,no,unfurnished
28,2,8400000,7950,5,2,yes,no,yes,yes,no,2,no,unfurnished
34,2,8120000,6840,5,1,yes,yes,yes,no,yes,1,no,furnished
89,2,6440000,8580,5,3,yes,no,no,no,no,2,no,furnished
143,3,5600000,4800,5,2,no,no,yes,yes,no,0,no,unfurnished
152,2,5565000,5400,5,1,yes,yes,yes,no,yes,0,yes,furnished
271,2,4340000,1905,5,1,no,no,yes,no,no,0,no,semi-furnished
340,2,3850000,5300,5,2,yes,no,no,no,no,0,no,semi-furnished
356,1,3773000,2520,5,2,no,no,yes,no,yes,1,no,furnished
536,2,1960000,3420,5,1,no,no,no,no,no,0,no,unfurnished
0,3,13300000,7420,4,2,yes,no,no,no,yes,2,yes,furnished
1,4,12250000,8960,4,4,yes,no,no,no,yes,3,no,furnished
3,2,12215000,7500,4,2,yes,no,yes,no,yes,3,yes,furnished
4,2,11410000,7420,4,1,yes,yes,yes,no,yes,2,no,furnished
6,4,10150000,8580,4,3,yes,no,no,no,yes,2,yes,semi-furnished
8,2,9870000,8100,4,1,yes,yes,yes,no,yes,2,yes,furnished
11,2,9681000,6000,4,3,yes,yes,yes,yes,no,2,no,semi-furnished
12,2,9310000,6550,4,2,yes,no,no,no,yes,1,yes,semi-furnished
13,2,9240000,3500,4,2,yes,no,no,yes,no,2,no,furnished
15,2,9100000,6000,4,1,yes,no,yes,no,no,2,no,semi-furnished
16,2,9100000,6600,4,2,yes,yes,yes,no,yes,1,yes,unfurnished
25,2,8540000,6540,4,2,yes,yes,yes,no,yes,2,yes,furnished
29,2,8400000,5500,4,2,yes,no,yes,no,yes,1,yes,semi-furnished
32,2,8295000,4880,4,2,yes,no,no,no,yes,1,yes,furnished
37,4,7980000,9000,4,2,yes,no,no,no,yes,2,no,furnished
39,4,7910000,6000,4,2,yes,no,no,no,yes,1,no,semi-furnished
43,4,7700000,6000,4,2,yes,no,no,no,no,2,no,semi-furnished
44,4,7560000,6000,4,2,yes,no,no,no,yes,1,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
491,1,2835000,2640,2,1,no,no,no,no,no,1,no,furnished
494,1,2730000,6800,2,1,yes,no,no,no,no,0,no,unfurnished
496,1,2695000,4000,2,1,yes,no,no,no,no,0,no,unfurnished
497,1,2660000,3934,2,1,yes,no,no,no,no,0,no,unfurnished
498,2,2660000,2000,2,1,yes,no,no,no,no,0,no,semi-furnished
502,1,2660000,3480,2,1,yes,no,no,no,no,1,no,semi-furnished
504,1,2653000,3185,2,1,yes,no,no,no,yes,0,no,unfurnished
506,1,2604000,2910,2,1,no,no,no,no,no,0,no,unfurnished
507,1,2590000,3600,2,1,yes,no,no,no,no,0,no,unfurnished
508,1,2590000,4400,2,1,yes,no,no,no,no,0,no,unfurnished
509,2,2590000,3600,2,2,yes,no,yes,no,no,1,no,furnished
512,2,2520000,3000,2,1,yes,no,no,no,no,0,no,furnished
516,1,2450000,3240,2,1,no,yes,no,no,no,1,no,unfurnished
517,1,2450000,3000,2,1,yes,no,no,no,no,1,no,unfurnished
518,1,2450000,3500,2,1,yes,yes,no,no,no,0,no,unfurnished
519,2,2450000,4840,2,1,yes,no,no,no,no,0,no,unfurnished
520,1,2450000,7700,2,1,yes,no,no,no,no,0,no,unfurnished
521,1,2408000,3635,2,1,no,no,no,no,no,0,no,unfurnished
524,1,2380000,3264,2,1,yes,no,no,no,no,0,no,unfurnished
525,1,2345000,3640,2,1,yes,no,no,no,no,0,no,unfurnished
526,1,2310000,3180,2,1,yes,no,no,no,no,0,no,unfurnished
527,1,2275000,1836,2,1,no,no,yes,no,no,0,no,semi-furnished
532,1,2135000,3000,2,1,no,no,no,no,no,0,no,unfurnished
535,1,2100000,3360,2,1,yes,no,no,no,no,1,no,unfurnished
538,1,1890000,3649,2,1,yes,no,no,no,no,0,no,unfurnished
539,1,1855000,2990,2,1,no,no,no,no,no,1,no,unfurnished
540,1,1820000,3000,2,1,yes,no,yes,no,no,2,no,unfurnished
542,1,1750000,3620,2,1,yes,no,no,no,no,0,no,unfurnished
445,1,3150000,3450,1,1,yes,no,no,no,no,0,no,furnished
528,1,2275000,3970,1,1,no,no,no,no,no,0,no,unfurnished

In [35]:
df.sort_values(by = ["price", "bedrooms"], ascending = True)

,stories,price,area,bedrooms,bathrooms,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
542,1,1750000,3620,2,1,yes,no,no,no,no,0,no,unfurnished
543,1,1750000,2910,3,1,no,no,no,no,no,0,no,furnished
544,2,1750000,3850,3,1,yes,no,no,no,no,0,no,unfurnished
541,1,1767150,2400,3,1,no,no,no,no,no,0,no,semi-furnished
540,1,1820000,3000,2,1,yes,no,yes,no,no,2,no,unfurnished
539,1,1855000,2990,2,1,no,no,no,no,no,1,no,unfurnished
538,1,1890000,3649,2,1,yes,no,no,no,no,0,no,unfurnished
537,2,1890000,1700,3,1,yes,no,no,no,no,0,no,unfurnished
536,2,1960000,3420,5,1,no,no,no,no,no,0,no,unfurnished
535,1,2100000,3360,2,1,yes,no,no,no,no,1,no,unfurnished
533,2,2100000,2400,3,1,yes,no,no,no,no,0,no,unfurnished
534,2,2100000,3000,4,1,yes,no,no,no,no,0,no,unfurnished
532,1,2135000,3000,2,1,no,no,no,no,no,0,no,unfurnished
531,1,2233000,5300,3,1,no,no,no,no,yes,0,yes,unfurnished
530,1,2240000,1950,3,1,no,no,no,yes,no,0,no,unfurnished
528,1,2275000,3970,1,1,no,no,no,no,no,0,no,unfurnished
527,1,2275000,1836,2,1,no,no,yes,no,no,0,no,semi-furnished
529,2,2275000,3970,3,1,yes,no,yes,no,no,0,no,unfurnished
526,1,2310000,3180,2,1,yes,no,no,no,no,0,no,unfurnished
525,1,2345000,3640,2,1,yes,no,no,no,no,0,no,unfurnished
524,1,2380000,3264,2,1,yes,no,no,no,no,0,no,unfurnished
522,2,2380000,2475,3,1,yes,no,no,no,no,0,no,furnished
523,2,2380000,2787,4,2,yes,no,no,no,no,0,no,furnished
521,1,2408000,3635,2,1,no,no,no,no,no,0,no,unfurnished
516,1,2450000,3240,2,1,no,yes,no,no,no,1,no,unfurnished
517,1,2450000,3000,2,1,yes,no,no,no,no,1,no,unfurnished
518,1,2450000,3500,2,1,yes,yes,no,no,no,0,no,unfurnished
519,2,2450000,4840,2,1,yes,no,no,no,no,0,no,unfurnished
520,1,2450000,7700,2,1,yes,no,no,no,no,0,no,unfurnished
515,2,2450000,3210,3,1,yes,no,yes,no,no,0,no,unfurnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
31,4,8400000,7000,3,1,yes,no,no,no,yes,2,no,semi-furnished
29,2,8400000,5500,4,2,yes,no,yes,no,yes,1,yes,semi-furnished
28,2,8400000,7950,5,2,yes,no,yes,yes,no,2,no,unfurnished
26,4,8463000,6000,3,2,yes,yes,yes,no,yes,0,yes,semi-furnished
25,2,8540000,6540,4,2,yes,yes,yes,no,yes,2,yes,furnished
24,2,8575000,8800,3,2,yes,no,no,no,yes,2,no,furnished
22,1,8645000,8050,3,1,yes,yes,yes,no,yes,1,no,furnished
23,2,8645000,4560,3,2,yes,yes,yes,no,yes,1,no,furnished
21,1,8680000,7155,3,2,yes,yes,yes,no,yes,2,no,unfurnished
20,2,8750000,4320,3,1,yes,no,yes,yes,no,2,no,semi-furnished
19,2,8855000,6420,3,2,yes,no,no,no,yes,1,yes,semi-furnished
18,2,8890000,4600,3,2,yes,yes,no,no,yes,2,no,furnished
17,4,8960000,8500,3,2,yes,no,no,no,yes,2,no,furnished
15,2,9100000,6000,4,1,yes,no,yes,no,no,2,no,semi-furnished
16,2,9100000,6600,4,2,yes,yes,yes,no,yes,1,yes,unfurnished
14,2,9240000,7800,3,2,yes,no,no,no,no,0,yes,semi-furnished
13,2,9240000,3500,4,2,yes,no,no,yes,no,2,no,furnished
12,2,9310000,6550,4,2,yes,no,no,no,yes,1,yes,semi-furnished
11,2,9681000,6000,4,3,yes,yes,yes,yes,no,2,no,semi-furnished
9,4,9800000,5750,3,2,yes,yes,no,no,yes,1,yes,unfurnished
10,2,9800000,13200,3,1,yes,no,yes,no,yes,2,yes,furnished
8,2,9870000,8100,4,1,yes,yes,yes,no,yes,2,yes,furnished
6,4,10150000,8580,4,3,yes,no,no,no,yes,2,yes,semi-furnished
7,2,10150000,16200,5,3,yes,no,no,no,no,0,no,unfurnished
5,1,10850000,7500,3,3,yes,no,yes,no,yes,2,yes,semi-furnished
4,2,11410000,7420,4,1,yes,yes,yes,no,yes,2,no,furnished
3,2,12215000,7500,4,2,yes,no,yes,no,yes,3,yes,furnished
2,2,12250000,9960,3,2,yes,no,yes,no,no,2,yes,semi-furnished
1,4,12250000,8960,4,4,yes,no,no,no,yes,3,no,furnished
0,3,13300000,7420,4,2,yes,no,no,no,yes,2,yes,furnished

Filetering rows of the dataframe based on conditions like

- price < 5000000
- bedrooms > 3

now we can use .loc for extracrion of rows

In [36]:
df.loc[df.price < 5000000]

,stories,price,area,bedrooms,bathrooms,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
195,2,4970000,4410,4,3,yes,no,yes,no,no,2,no,semi-furnished
196,1,4970000,7686,3,1,yes,yes,yes,yes,no,0,no,semi-furnished
197,2,4956000,2800,3,2,no,no,yes,no,yes,1,no,semi-furnished
198,2,4935000,5948,3,1,yes,no,no,no,yes,0,no,semi-furnished
199,2,4907000,4200,3,1,yes,no,no,no,no,1,no,furnished
200,2,4900000,4520,3,1,yes,no,yes,no,yes,0,no,semi-furnished
201,2,4900000,4095,3,1,no,yes,yes,no,yes,0,no,semi-furnished
202,1,4900000,4120,2,1,yes,no,yes,no,no,1,no,semi-furnished
203,2,4900000,5400,4,1,yes,no,no,no,no,0,no,semi-furnished
204,1,4900000,4770,3,1,yes,yes,yes,no,no,0,no,semi-furnished
205,1,4900000,6300,3,1,yes,no,no,no,yes,2,no,semi-furnished
206,1,4900000,5800,2,1,yes,yes,yes,no,yes,0,no,semi-furnished
207,2,4900000,3000,3,1,yes,no,yes,no,yes,0,no,semi-furnished
208,3,4900000,2970,3,1,yes,no,no,no,no,0,no,semi-furnished
209,1,4900000,6720,3,1,yes,no,no,no,no,0,no,unfurnished
210,2,4900000,4646,3,1,yes,yes,yes,no,no,2,no,semi-furnished
211,1,4900000,12900,3,1,yes,no,no,no,no,2,no,furnished
212,2,4893000,3420,4,2,yes,no,yes,no,yes,2,no,semi-furnished
213,1,4893000,4995,4,2,yes,no,yes,no,no,0,no,semi-furnished
214,1,4865000,4350,2,1,yes,no,yes,no,no,0,no,unfurnished
215,3,4830000,4160,3,1,yes,no,no,no,no,0,no,unfurnished
216,1,4830000,6040,3,1,yes,no,no,no,no,2,yes,semi-furnished
217,2,4830000,6862,3,1,yes,no,no,no,yes,2,yes,furnished
218,1,4830000,4815,2,1,yes,no,no,no,yes,0,yes,semi-furnished
219,2,4795000,7000,3,1,yes,no,yes,no,no,0,no,unfurnished
220,4,4795000,8100,4,1,yes,no,yes,no,yes,2,no,semi-furnished
221,2,4767000,3420,4,2,yes,no,no,no,no,0,no,semi-furnished
222,1,4760000,9166,2,1,yes,no,yes,no,yes,2,no,semi-furnished
223,2,4760000,6321,3,1,yes,no,yes,no,yes,1,no,furnished
224,1,4760000,10240,2,1,yes,no,no,no,yes,2,yes,unfurnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
515,2,2450000,3210,3,1,yes,no,yes,no,no,0,no,unfurnished
516,1,2450000,3240,2,1,no,yes,no,no,no,1,no,unfurnished
517,1,2450000,3000,2,1,yes,no,no,no,no,1,no,unfurnished
518,1,2450000,3500,2,1,yes,yes,no,no,no,0,no,unfurnished
519,2,2450000,4840,2,1,yes,no,no,no,no,0,no,unfurnished
520,1,2450000,7700,2,1,yes,no,no,no,no,0,no,unfurnished
521,1,2408000,3635,2,1,no,no,no,no,no,0,no,unfurnished
522,2,2380000,2475,3,1,yes,no,no,no,no,0,no,furnished
523,2,2380000,2787,4,2,yes,no,no,no,no,0,no,furnished
524,1,2380000,3264,2,1,yes,no,no,no,no,0,no,unfurnished
525,1,2345000,3640,2,1,yes,no,no,no,no,0,no,unfurnished
526,1,2310000,3180,2,1,yes,no,no,no,no,0,no,unfurnished
527,1,2275000,1836,2,1,no,no,yes,no,no,0,no,semi-furnished
528,1,2275000,3970,1,1,no,no,no,no,no,0,no,unfurnished
529,2,2275000,3970,3,1,yes,no,yes,no,no,0,no,unfurnished
530,1,2240000,1950,3,1,no,no,no,yes,no,0,no,unfurnished
531,1,2233000,5300,3,1,no,no,no,no,yes,0,yes,unfurnished
532,1,2135000,3000,2,1,no,no,no,no,no,0,no,unfurnished
533,2,2100000,2400,3,1,yes,no,no,no,no,0,no,unfurnished
534,2,2100000,3000,4,1,yes,no,no,no,no,0,no,unfurnished
535,1,2100000,3360,2,1,yes,no,no,no,no,1,no,unfurnished
536,2,1960000,3420,5,1,no,no,no,no,no,0,no,unfurnished
537,2,1890000,1700,3,1,yes,no,no,no,no,0,no,unfurnished
538,1,1890000,3649,2,1,yes,no,no,no,no,0,no,unfurnished
539,1,1855000,2990,2,1,no,no,no,no,no,1,no,unfurnished
540,1,1820000,3000,2,1,yes,no,yes,no,no,2,no,unfurnished
541,1,1767150,2400,3,1,no,no,no,no,no,0,no,semi-furnished
542,1,1750000,3620,2,1,yes,no,no,no,no,0,no,unfurnished
543,1,1750000,2910,3,1,no,no,no,no,no,0,no,furnished
544,2,1750000,3850,3,1,yes,no,no,no,no,0,no,unfurnished

In [37]:
df.loc[df["price"]< 5000000]

,stories,price,area,bedrooms,bathrooms,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
195,2,4970000,4410,4,3,yes,no,yes,no,no,2,no,semi-furnished
196,1,4970000,7686,3,1,yes,yes,yes,yes,no,0,no,semi-furnished
197,2,4956000,2800,3,2,no,no,yes,no,yes,1,no,semi-furnished
198,2,4935000,5948,3,1,yes,no,no,no,yes,0,no,semi-furnished
199,2,4907000,4200,3,1,yes,no,no,no,no,1,no,furnished
200,2,4900000,4520,3,1,yes,no,yes,no,yes,0,no,semi-furnished
201,2,4900000,4095,3,1,no,yes,yes,no,yes,0,no,semi-furnished
202,1,4900000,4120,2,1,yes,no,yes,no,no,1,no,semi-furnished
203,2,4900000,5400,4,1,yes,no,no,no,no,0,no,semi-furnished
204,1,4900000,4770,3,1,yes,yes,yes,no,no,0,no,semi-furnished
205,1,4900000,6300,3,1,yes,no,no,no,yes,2,no,semi-furnished
206,1,4900000,5800,2,1,yes,yes,yes,no,yes,0,no,semi-furnished
207,2,4900000,3000,3,1,yes,no,yes,no,yes,0,no,semi-furnished
208,3,4900000,2970,3,1,yes,no,no,no,no,0,no,semi-furnished
209,1,4900000,6720,3,1,yes,no,no,no,no,0,no,unfurnished
210,2,4900000,4646,3,1,yes,yes,yes,no,no,2,no,semi-furnished
211,1,4900000,12900,3,1,yes,no,no,no,no,2,no,furnished
212,2,4893000,3420,4,2,yes,no,yes,no,yes,2,no,semi-furnished
213,1,4893000,4995,4,2,yes,no,yes,no,no,0,no,semi-furnished
214,1,4865000,4350,2,1,yes,no,yes,no,no,0,no,unfurnished
215,3,4830000,4160,3,1,yes,no,no,no,no,0,no,unfurnished
216,1,4830000,6040,3,1,yes,no,no,no,no,2,yes,semi-furnished
217,2,4830000,6862,3,1,yes,no,no,no,yes,2,yes,furnished
218,1,4830000,4815,2,1,yes,no,no,no,yes,0,yes,semi-furnished
219,2,4795000,7000,3,1,yes,no,yes,no,no,0,no,unfurnished
220,4,4795000,8100,4,1,yes,no,yes,no,yes,2,no,semi-furnished
221,2,4767000,3420,4,2,yes,no,no,no,no,0,no,semi-furnished
222,1,4760000,9166,2,1,yes,no,yes,no,yes,2,no,semi-furnished
223,2,4760000,6321,3,1,yes,no,yes,no,yes,1,no,furnished
224,1,4760000,10240,2,1,yes,no,no,no,yes,2,yes,unfurnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
515,2,2450000,3210,3,1,yes,no,yes,no,no,0,no,unfurnished
516,1,2450000,3240,2,1,no,yes,no,no,no,1,no,unfurnished
517,1,2450000,3000,2,1,yes,no,no,no,no,1,no,unfurnished
518,1,2450000,3500,2,1,yes,yes,no,no,no,0,no,unfurnished
519,2,2450000,4840,2,1,yes,no,no,no,no,0,no,unfurnished
520,1,2450000,7700,2,1,yes,no,no,no,no,0,no,unfurnished
521,1,2408000,3635,2,1,no,no,no,no,no,0,no,unfurnished
522,2,2380000,2475,3,1,yes,no,no,no,no,0,no,furnished
523,2,2380000,2787,4,2,yes,no,no,no,no,0,no,furnished
524,1,2380000,3264,2,1,yes,no,no,no,no,0,no,unfurnished
525,1,2345000,3640,2,1,yes,no,no,no,no,0,no,unfurnished
526,1,2310000,3180,2,1,yes,no,no,no,no,0,no,unfurnished
527,1,2275000,1836,2,1,no,no,yes,no,no,0,no,semi-furnished
528,1,2275000,3970,1,1,no,no,no,no,no,0,no,unfurnished
529,2,2275000,3970,3,1,yes,no,yes,no,no,0,no,unfurnished
530,1,2240000,1950,3,1,no,no,no,yes,no,0,no,unfurnished
531,1,2233000,5300,3,1,no,no,no,no,yes,0,yes,unfurnished
532,1,2135000,3000,2,1,no,no,no,no,no,0,no,unfurnished
533,2,2100000,2400,3,1,yes,no,no,no,no,0,no,unfurnished
534,2,2100000,3000,4,1,yes,no,no,no,no,0,no,unfurnished
535,1,2100000,3360,2,1,yes,no,no,no,no,1,no,unfurnished
536,2,1960000,3420,5,1,no,no,no,no,no,0,no,unfurnished
537,2,1890000,1700,3,1,yes,no,no,no,no,0,no,unfurnished
538,1,1890000,3649,2,1,yes,no,no,no,no,0,no,unfurnished
539,1,1855000,2990,2,1,no,no,no,no,no,1,no,unfurnished
540,1,1820000,3000,2,1,yes,no,yes,no,no,2,no,unfurnished
541,1,1767150,2400,3,1,no,no,no,no,no,0,no,semi-furnished
542,1,1750000,3620,2,1,yes,no,no,no,no,0,no,unfurnished
543,1,1750000,2910,3,1,no,no,no,no,no,0,no,furnished
544,2,1750000,3850,3,1,yes,no,no,no,no,0,no,unfurnished

#### filetring based on multiple conditions using "&" ,"or(|)" operaters

In [38]:

df.loc[(df.price > 4000000) & (df.bedrooms==3)]

,stories,price,area,bedrooms,bathrooms,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
2,2,12250000,9960,3,2,yes,no,yes,no,no,2,yes,semi-furnished
5,1,10850000,7500,3,3,yes,no,yes,no,yes,2,yes,semi-furnished
9,4,9800000,5750,3,2,yes,yes,no,no,yes,1,yes,unfurnished
10,2,9800000,13200,3,1,yes,no,yes,no,yes,2,yes,furnished
14,2,9240000,7800,3,2,yes,no,no,no,no,0,yes,semi-furnished
17,4,8960000,8500,3,2,yes,no,no,no,yes,2,no,furnished
18,2,8890000,4600,3,2,yes,yes,no,no,yes,2,no,furnished
19,2,8855000,6420,3,2,yes,no,no,no,yes,1,yes,semi-furnished
20,2,8750000,4320,3,1,yes,no,yes,yes,no,2,no,semi-furnished
21,1,8680000,7155,3,2,yes,yes,yes,no,yes,2,no,unfurnished
22,1,8645000,8050,3,1,yes,yes,yes,no,yes,1,no,furnished
23,2,8645000,4560,3,2,yes,yes,yes,no,yes,1,no,furnished
24,2,8575000,8800,3,2,yes,no,no,no,yes,2,no,furnished
26,4,8463000,6000,3,2,yes,yes,yes,no,yes,0,yes,semi-furnished
27,1,8400000,8875,3,1,yes,no,no,no,no,1,no,semi-furnished
30,4,8400000,7475,3,2,yes,no,no,no,yes,2,no,unfurnished
31,4,8400000,7000,3,1,yes,no,no,no,yes,2,no,semi-furnished
33,2,8190000,5960,3,3,yes,yes,yes,no,no,1,no,unfurnished
35,4,8080940,7000,3,2,yes,no,no,no,yes,2,no,furnished
36,3,8043000,7482,3,2,yes,no,no,yes,no,1,yes,furnished
38,4,7962500,6000,3,1,yes,yes,no,no,yes,2,no,unfurnished
40,2,7875000,6550,3,1,yes,no,yes,no,yes,0,yes,furnished
41,4,7840000,6360,3,2,yes,no,no,no,yes,0,yes,furnished
42,4,7700000,6480,3,2,yes,no,no,no,yes,2,no,unfurnished
45,3,7560000,6000,3,2,yes,no,no,no,yes,0,no,semi-furnished
46,4,7525000,6000,3,2,yes,no,no,no,yes,1,no,furnished
47,4,7490000,6600,3,1,yes,no,no,no,yes,3,yes,furnished
48,2,7455000,4300,3,2,yes,no,yes,no,no,1,no,unfurnished
49,1,7420000,7440,3,2,yes,yes,yes,no,yes,0,yes,semi-furnished
50,4,7420000,7440,3,2,yes,no,no,no,no,1,yes,unfurnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
282,2,4270000,2175,3,1,no,yes,yes,no,yes,0,no,unfurnished
285,2,4235000,6650,3,1,yes,yes,no,no,no,0,no,semi-furnished
286,1,4235000,2787,3,1,yes,no,yes,no,no,0,yes,furnished
287,2,4200000,5500,3,1,yes,no,no,no,yes,0,no,unfurnished
288,2,4200000,5040,3,1,yes,no,yes,no,yes,0,no,unfurnished
291,2,4200000,2953,3,1,yes,no,yes,no,yes,0,no,unfurnished
295,2,4200000,2325,3,1,no,no,no,no,no,0,no,semi-furnished
296,2,4200000,4600,3,2,yes,no,no,no,yes,1,no,semi-furnished
297,2,4200000,3640,3,2,yes,no,yes,no,no,0,no,unfurnished
298,1,4200000,5800,3,1,yes,no,no,yes,no,2,no,semi-furnished
299,1,4200000,7000,3,1,yes,no,no,no,no,3,no,furnished
300,3,4200000,4079,3,1,yes,no,no,no,no,0,no,semi-furnished
301,2,4200000,3520,3,1,yes,no,no,no,no,0,yes,semi-furnished
302,3,4200000,2145,3,1,yes,no,no,no,no,1,yes,unfurnished
303,1,4200000,4500,3,1,yes,no,yes,no,no,0,no,furnished
304,1,4193000,8250,3,1,yes,no,yes,no,no,3,no,semi-furnished
305,2,4193000,3450,3,1,yes,no,no,no,no,1,no,semi-furnished
306,2,4165000,4840,3,1,yes,no,no,no,no,1,no,semi-furnished
307,2,4165000,4080,3,1,yes,no,no,no,no,2,no,semi-furnished
308,2,4165000,4046,3,1,yes,no,yes,no,no,1,no,semi-furnished
310,1,4130000,5985,3,1,yes,no,yes,no,no,0,no,semi-furnished
312,1,4098500,3600,3,1,yes,no,yes,no,yes,0,yes,furnished
313,2,4095000,3680,3,2,yes,no,no,no,no,0,no,semi-furnished
317,2,4060000,4992,3,2,yes,no,no,no,no,2,no,unfurnished
318,1,4060000,4340,3,1,yes,no,no,no,no,0,no,semi-furnished
320,2,4060000,4320,3,1,yes,no,no,no,no,2,yes,furnished
321,2,4025000,3630,3,2,yes,no,no,yes,no,2,no,semi-furnished
322,1,4025000,3460,3,2,yes,no,yes,no,yes,1,no,furnished
323,1,4025000,5400,3,1,yes,no,no,no,no,3,no,semi-furnished
324,2,4007500,4500,3,1,no,no,yes,no,yes,0,no,semi-furnished

In [39]:
df.loc[(df.bedrooms>3) | (df.stories<1)]

,stories,price,area,bedrooms,bathrooms,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,3,13300000,7420,4,2,yes,no,no,no,yes,2,yes,furnished
1,4,12250000,8960,4,4,yes,no,no,no,yes,3,no,furnished
3,2,12215000,7500,4,2,yes,no,yes,no,yes,3,yes,furnished
4,2,11410000,7420,4,1,yes,yes,yes,no,yes,2,no,furnished
6,4,10150000,8580,4,3,yes,no,no,no,yes,2,yes,semi-furnished
7,2,10150000,16200,5,3,yes,no,no,no,no,0,no,unfurnished
8,2,9870000,8100,4,1,yes,yes,yes,no,yes,2,yes,furnished
11,2,9681000,6000,4,3,yes,yes,yes,yes,no,2,no,semi-furnished
12,2,9310000,6550,4,2,yes,no,no,no,yes,1,yes,semi-furnished
13,2,9240000,3500,4,2,yes,no,no,yes,no,2,no,furnished
15,2,9100000,6000,4,1,yes,no,yes,no,no,2,no,semi-furnished
16,2,9100000,6600,4,2,yes,yes,yes,no,yes,1,yes,unfurnished
25,2,8540000,6540,4,2,yes,yes,yes,no,yes,2,yes,furnished
28,2,8400000,7950,5,2,yes,no,yes,yes,no,2,no,unfurnished
29,2,8400000,5500,4,2,yes,no,yes,no,yes,1,yes,semi-furnished
32,2,8295000,4880,4,2,yes,no,no,no,yes,1,yes,furnished
34,2,8120000,6840,5,1,yes,yes,yes,no,yes,1,no,furnished
37,4,7980000,9000,4,2,yes,no,no,no,yes,2,no,furnished
39,4,7910000,6000,4,2,yes,no,no,no,yes,1,no,semi-furnished
43,4,7700000,6000,4,2,yes,no,no,no,no,2,no,semi-furnished
44,4,7560000,6000,4,2,yes,no,no,no,yes,1,no,furnished
52,4,7350000,6000,4,2,yes,yes,no,no,yes,1,no,furnished
56,2,7343000,11440,4,1,yes,no,yes,no,no,1,yes,semi-furnished
57,4,7245000,9000,4,2,yes,yes,no,no,yes,1,yes,furnished
58,4,7210000,7680,4,2,yes,yes,no,no,yes,1,no,semi-furnished
62,2,7070000,6240,4,2,yes,no,no,no,yes,1,no,furnished
63,3,7035000,6360,4,2,yes,no,no,no,yes,2,yes,furnished
69,2,6790000,12090,4,2,yes,no,no,no,no,2,yes,furnished
71,4,6755000,6000,4,2,yes,no,no,no,yes,0,no,unfurnished
75,2,6650000,4260,4,2,yes,no,no,yes,no,0,no,semi-furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
294,2,4200000,4000,4,2,no,no,no,no,no,0,no,semi-furnished
309,2,4130000,4632,4,1,yes,no,no,no,yes,0,no,semi-furnished
316,2,4060000,5900,4,2,no,no,yes,no,no,1,no,unfurnished
319,3,4060000,3000,4,1,yes,no,yes,no,yes,2,no,semi-furnished
325,2,4007500,3460,4,1,yes,no,no,no,yes,0,no,semi-furnished
326,1,3990000,4100,4,1,no,no,yes,no,no,0,no,unfurnished
332,2,3920000,5500,4,1,yes,yes,yes,no,no,0,no,semi-furnished
337,1,3920000,2145,4,2,yes,no,yes,no,no,0,yes,unfurnished
339,2,3885000,3180,4,2,yes,no,no,no,no,0,no,furnished
340,2,3850000,5300,5,2,yes,no,no,no,no,0,no,semi-furnished
356,1,3773000,2520,5,2,no,no,yes,no,yes,1,no,furnished
357,2,3773000,6930,4,1,no,no,no,no,no,1,no,furnished
383,2,3570000,4500,4,2,yes,no,yes,no,no,2,no,furnished
389,2,3500000,4600,4,1,yes,no,no,no,no,0,no,semi-furnished
395,2,3500000,3600,6,1,yes,no,no,no,no,1,no,unfurnished
418,2,3360000,3500,4,1,yes,no,no,no,yes,2,no,unfurnished
419,3,3360000,4960,4,1,no,no,no,no,no,0,no,semi-furnished
429,2,3325000,4775,4,1,yes,no,no,no,no,0,no,unfurnished
431,2,3290000,3180,4,1,yes,no,yes,no,yes,0,no,unfurnished
433,2,3290000,3480,4,1,no,no,no,no,no,1,no,semi-furnished
434,2,3290000,3792,4,1,yes,no,no,no,no,0,no,semi-furnished
440,2,3234000,3640,4,1,yes,no,yes,no,no,0,no,unfurnished
472,2,3010000,3630,4,1,yes,no,no,no,no,3,no,semi-furnished
474,2,2975000,4352,4,1,no,no,no,no,no,1,no,unfurnished
479,2,2940000,3660,4,1,no,no,no,no,no,0,no,unfurnished
487,2,2870000,5400,4,1,yes,no,no,no,no,0,no,unfurnished
488,3,2852500,5200,4,1,yes,no,no,no,no,0,no,unfurnished
523,2,2380000,2787,4,2,yes,no,no,no,no,0,no,furnished
534,2,2100000,3000,4,1,yes,no,no,no,no,0,no,unfurnished
536,2,1960000,3420,5,1,no,no,no,no,no,0,no,unfurnished

In [40]:
# filtering rows on condition and selecting only required columns 
df.loc[(df.bedrooms>2) & (df.stories == 1 ), ["price", "area","parking"]]

        price   area  parking
5    10850000   7500        2
21    8680000   7155        2
22    8645000   8050        1
27    8400000   8875        1
49    7420000   7440        0
64    7000000  11175        1
67    6895000   7700        2
68    6860000   6000        1
78    6650000   5700        2
82    6615000  10500        1
87    6475000   3960        2
88    6475000   7410        2
93    6300000   7200        3
96    6300000   9000        1
97    6300000   6400        1
100   6230000   6600        0
104   6195000   5500        2
106   6160000   5450        0
110   6090000   6600        2
113   6083000   9620        2
115   6020000   8000        2
116   6020000   6900        0
118   5950000   6420        0
119   5950000   7020        2
120   5950000   6540        2
122   5950000   6254        1
125   5943000  15600        2
126   5880000   7160        2
130   5866000   4800        0
134   5803000   7000        2
..        ...    ...      ...
356   3773000   2520        1
359   3710000   3600        1
361   3710000   6020        0
379   3633000   3520        2
386   3535000   3850        2
393   3500000   7424        0
394   3500000   3480        0
403   3500000  12944        0
405   3465000   3060        0
410   3430000   3850        0
416   3395000   3450        2
423   3360000   3750        0
426   3353000   2700        0
432   3290000   6060        0
437   3290000   5880        1
443   3220000   4320        1
455   3129000   5495        0
456   3118850   2398        0
457   3115000   3000        0
470   3010000   5076        0
493   2800000   3960        0
500   2660000   2800        0
501   2660000   2430        0
503   2660000   4000        0
510   2520000   2880        0
511   2520000   3180        0
530   2240000   1950        0
531   2233000   5300        0
541   1767150   2400        0
543   1750000   2910        0

[110 rows x 3 columns]

In [41]:
df.loc[(df.bedrooms == 4)]

,stories,price,area,bedrooms,bathrooms,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,3,13300000,7420,4,2,yes,no,no,no,yes,2,yes,furnished
1,4,12250000,8960,4,4,yes,no,no,no,yes,3,no,furnished
3,2,12215000,7500,4,2,yes,no,yes,no,yes,3,yes,furnished
4,2,11410000,7420,4,1,yes,yes,yes,no,yes,2,no,furnished
6,4,10150000,8580,4,3,yes,no,no,no,yes,2,yes,semi-furnished
8,2,9870000,8100,4,1,yes,yes,yes,no,yes,2,yes,furnished
11,2,9681000,6000,4,3,yes,yes,yes,yes,no,2,no,semi-furnished
12,2,9310000,6550,4,2,yes,no,no,no,yes,1,yes,semi-furnished
13,2,9240000,3500,4,2,yes,no,no,yes,no,2,no,furnished
15,2,9100000,6000,4,1,yes,no,yes,no,no,2,no,semi-furnished
16,2,9100000,6600,4,2,yes,yes,yes,no,yes,1,yes,unfurnished
25,2,8540000,6540,4,2,yes,yes,yes,no,yes,2,yes,furnished
29,2,8400000,5500,4,2,yes,no,yes,no,yes,1,yes,semi-furnished
32,2,8295000,4880,4,2,yes,no,no,no,yes,1,yes,furnished
37,4,7980000,9000,4,2,yes,no,no,no,yes,2,no,furnished
39,4,7910000,6000,4,2,yes,no,no,no,yes,1,no,semi-furnished
43,4,7700000,6000,4,2,yes,no,no,no,no,2,no,semi-furnished
44,4,7560000,6000,4,2,yes,no,no,no,yes,1,no,furnished
52,4,7350000,6000,4,2,yes,yes,no,no,yes,1,no,furnished
56,2,7343000,11440,4,1,yes,no,yes,no,no,1,yes,semi-furnished
57,4,7245000,9000,4,2,yes,yes,no,no,yes,1,yes,furnished
58,4,7210000,7680,4,2,yes,yes,no,no,yes,1,no,semi-furnished
62,2,7070000,6240,4,2,yes,no,no,no,yes,1,no,furnished
63,3,7035000,6360,4,2,yes,no,no,no,yes,2,yes,furnished
69,2,6790000,12090,4,2,yes,no,no,no,no,2,yes,furnished
71,4,6755000,6000,4,2,yes,no,no,no,yes,0,no,unfurnished
75,2,6650000,4260,4,2,yes,no,no,yes,no,0,no,semi-furnished
94,4,6300000,6000,4,2,yes,no,no,no,no,1,no,semi-furnished
99,3,6265000,6000,4,1,yes,yes,yes,no,no,0,yes,unfurnished
106,1,6160000,5450,4,2,yes,no,yes,no,yes,0,yes,semi-furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
274,2,4340000,6450,4,1,yes,no,no,no,no,0,no,semi-furnished
283,2,4270000,4360,4,1,yes,no,no,no,no,0,no,furnished
290,2,4200000,2610,4,3,no,no,no,no,no,0,no,semi-furnished
292,2,4200000,2747,4,2,no,no,no,no,no,0,no,semi-furnished
294,2,4200000,4000,4,2,no,no,no,no,no,0,no,semi-furnished
309,2,4130000,4632,4,1,yes,no,no,no,yes,0,no,semi-furnished
316,2,4060000,5900,4,2,no,no,yes,no,no,1,no,unfurnished
319,3,4060000,3000,4,1,yes,no,yes,no,yes,2,no,semi-furnished
325,2,4007500,3460,4,1,yes,no,no,no,yes,0,no,semi-furnished
326,1,3990000,4100,4,1,no,no,yes,no,no,0,no,unfurnished
332,2,3920000,5500,4,1,yes,yes,yes,no,no,0,no,semi-furnished
337,1,3920000,2145,4,2,yes,no,yes,no,no,0,yes,unfurnished
339,2,3885000,3180,4,2,yes,no,no,no,no,0,no,furnished
357,2,3773000,6930,4,1,no,no,no,no,no,1,no,furnished
383,2,3570000,4500,4,2,yes,no,yes,no,no,2,no,furnished
389,2,3500000,4600,4,1,yes,no,no,no,no,0,no,semi-furnished
418,2,3360000,3500,4,1,yes,no,no,no,yes,2,no,unfurnished
419,3,3360000,4960,4,1,no,no,no,no,no,0,no,semi-furnished
429,2,3325000,4775,4,1,yes,no,no,no,no,0,no,unfurnished
431,2,3290000,3180,4,1,yes,no,yes,no,yes,0,no,unfurnished
433,2,3290000,3480,4,1,no,no,no,no,no,1,no,semi-furnished
434,2,3290000,3792,4,1,yes,no,no,no,no,0,no,semi-furnished
440,2,3234000,3640,4,1,yes,no,yes,no,no,0,no,unfurnished
472,2,3010000,3630,4,1,yes,no,no,no,no,3,no,semi-furnished
474,2,2975000,4352,4,1,no,no,no,no,no,1,no,unfurnished
479,2,2940000,3660,4,1,no,no,no,no,no,0,no,unfurnished
487,2,2870000,5400,4,1,yes,no,no,no,no,0,no,unfurnished
488,3,2852500,5200,4,1,yes,no,no,no,no,0,no,unfurnished
523,2,2380000,2787,4,2,yes,no,no,no,no,0,no,furnished
534,2,2100000,3000,4,1,yes,no,no,no,no,0,no,unfurnished